version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    container_name: django-server
    depends_on:
      - redis

  redis:
    image: redis:7.2.4-alpine
    container_name: redis-server

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Amazon

  celery:
    build: .
    container_name: celeryserver
    volumes:
      - .:/app
    command: celery -A project worker -l INFO
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    depends_on:
      - backend
    working_dir: /app


volumes:
  postgres_data: