# 1 start docker kernal + python
FROM python:3.12.1-slim-bullseye

# show logs:python
ENV PYTHONUNBUFFERED = 1

# update kernal + install
RUN apt-get update && apt-get -y install gcc libpq-dev

#folder for my project 
WORKDIR /app

#copy Requirments
COPY requirments.txt /app/requirments.txt

# install req
RUN pip install -r /app/requirments.txt

#Copy all project files
COPY . /app/